"""
CEO Briefing Generator - AI Employee Gold Tier
Runs every Sunday at 11:00 PM automatically.
Generates a "Monday Morning CEO Briefing" with weekly audit.

HOW IT WORKS:
1. Reads Business_Goals.md for context
2. Scans Done/ folder for this week's completed tasks
3. Reads Logs/ for activity summary
4. Uses Claude API to generate executive briefing
5. Saves to vault/Briefings/YYYY-MM-DD_Monday_Briefing.md
"""

import os
from pathlib import Path
from datetime import datetime, timedelta
import anthropic

# Paths
BASE_DIR = Path(__file__).parent.parent
VAULT_DIR = BASE_DIR / "vault"
DONE_DIR = VAULT_DIR / "Done"
LOGS_DIR = VAULT_DIR / "Logs"
BRIEFINGS_DIR = VAULT_DIR / "Briefings"
GOALS_FILE = VAULT_DIR / "Business_Goals.md"
DASHBOARD_FILE = VAULT_DIR / "Dashboard.md"
ENV_FILE = BASE_DIR / ".env"


def load_env():
    env_vars = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding='utf-8').splitlines():
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                env_vars[key.strip()] = value.strip().strip('"')
    return env_vars


def get_this_week_files(folder):
    """Get files created/modified in the last 7 days."""
    week_ago = datetime.now() - timedelta(days=7)
    files = []
    if folder.exists():
        for f in folder.iterdir():
            if f.is_file() and f.suffix == '.md':
                mtime = datetime.fromtimestamp(f.stat().st_mtime)
                if mtime >= week_ago:
                    files.append(f.name)
    return files


def get_weekly_logs():
    """Get log content from this week."""
    logs = ""
    week_ago = datetime.now() - timedelta(days=7)
    if LOGS_DIR.exists():
        for log_file in sorted(LOGS_DIR.iterdir()):
            if log_file.is_file() and log_file.suffix == '.md':
                try:
                    date_str = log_file.stem
                    file_date = datetime.strptime(date_str, '%Y-%m-%d')
                    if file_date >= week_ago:
                        logs += f"\n### {date_str}\n"
                        logs += log_file.read_text(encoding='utf-8')[:500]
                except (ValueError, Exception):
                    pass
    return logs or "No logs found for this week."


def generate_briefing(api_key, goals, completed_tasks, email_tasks, linkedin_tasks, logs):
    """Generate CEO briefing using Claude API."""
    client = anthropic.Anthropic(api_key=api_key)

    today = datetime.now().strftime("%B %d, %Y")
    next_monday = (datetime.now() + timedelta(days=(7 - datetime.now().weekday()))).strftime("%B %d, %Y")

    prompt = f"""You are an AI Employee generating a weekly CEO briefing report.

Today: {today}
Reporting period: Last 7 days

BUSINESS GOALS:
{goals}

COMPLETED TASKS THIS WEEK ({len(completed_tasks)} total):
{chr(10).join(f'- {t}' for t in completed_tasks[:20])}

EMAIL TASKS PROCESSED: {len(email_tasks)}
LINKEDIN POSTS: {len(linkedin_tasks)}

ACTIVITY LOGS:
{logs[:1000]}

Generate a professional "Monday Morning CEO Briefing" in markdown format with these sections:

# Monday Morning CEO Briefing — {next_monday}

## Executive Summary
(2-3 sentences overview)

## This Week's Performance
(tasks completed, emails handled, LinkedIn posts)

## Business Goals Progress
(based on goals provided)

## Bottlenecks & Issues
(any failures, errors, or slow areas noticed)

## Proactive Suggestions
(2-3 specific actionable suggestions based on the data)

## Next Week Preview
(what to focus on)

---
*Generated by AI Employee | {today}*

Keep it professional, data-driven, and actionable."""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1000,
        messages=[{"role": "user", "content": prompt}]
    )
    return message.content[0].text.strip()


def generate_fallback_briefing(completed_tasks, email_tasks, linkedin_tasks):
    """Fallback briefing without API."""
    today = datetime.now().strftime("%B %d, %Y")
    next_monday = (datetime.now() + timedelta(days=(7 - datetime.now().weekday()))).strftime("%B %d, %Y")

    return f"""# Monday Morning CEO Briefing — {next_monday}

## Executive Summary
Your AI Employee has been active this week, processing tasks, emails, and maintaining your LinkedIn presence autonomously.

## This Week's Performance
- **Total Tasks Completed:** {len(completed_tasks)}
- **Emails Processed:** {len(email_tasks)}
- **LinkedIn Posts Published:** {len(linkedin_tasks)}

## Business Goals Progress
- Monthly revenue target: In progress
- Customer acquisition: Emails handled automatically
- LinkedIn presence: {len(linkedin_tasks)} posts published this week

## Bottlenecks & Issues
- Review any failed email replies in vault/Logs/
- Check Pending_Approval folder for tasks awaiting review

## Proactive Suggestions
1. Review completed tasks in vault/Done/ to ensure quality
2. Check LinkedIn engagement on posts published this week
3. Update Business_Goals.md with latest revenue figures

## Next Week Preview
- Continue automated email responses
- Daily LinkedIn posting at 9:00 AM
- Monitor for sensitive tasks requiring approval

---
*Generated by AI Employee | {today}*
"""


def update_dashboard(briefing_file):
    """Update dashboard with briefing status."""
    if DASHBOARD_FILE.exists():
        content = DASHBOARD_FILE.read_text(encoding='utf-8')
        lines = content.splitlines()
        updated = []
        added = False
        for line in lines:
            updated.append(line)
            if line.startswith("## Recent Activity") and not added:
                updated.append(
                    f"- [CEO Briefing Generated] {briefing_file.name} "
                    f"({datetime.now().strftime('%Y-%m-%d %H:%M')})"
                )
                added = True
        DASHBOARD_FILE.write_text('\n'.join(updated), encoding='utf-8')


def log_action(status, message):
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    log_file = LOGS_DIR / f"{datetime.now().strftime('%Y-%m-%d')}.md"
    entry = f"- [{datetime.now().strftime('%H:%M:%S')}] CEOBriefing | {status} | {message}\n"
    with open(log_file, 'a', encoding='utf-8') as f:
        f.write(entry)


def main():
    print("=" * 55)
    print("  CEO Briefing Generator - AI Employee Gold Tier")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 55)

    # Check if this week's briefing already exists
    next_monday = datetime.now() + timedelta(days=(7 - datetime.now().weekday()))
    briefing_filename = f"{next_monday.strftime('%Y-%m-%d')}_Monday_Briefing.md"
    briefing_path = BRIEFINGS_DIR / briefing_filename

    if briefing_path.exists():
        print(f"[SKIP] Briefing already exists: {briefing_filename}")
        return

    BRIEFINGS_DIR.mkdir(parents=True, exist_ok=True)

    # Gather data
    print("[DATA] Reading Business Goals...")
    goals = GOALS_FILE.read_text(encoding='utf-8') if GOALS_FILE.exists() else "No goals file found."

    print("[DATA] Scanning Done folder...")
    all_done = get_this_week_files(DONE_DIR)
    email_tasks = [f for f in all_done if f.startswith('email_')]
    linkedin_tasks = [f for f in all_done if 'linkedin' in f.lower()]
    other_tasks = [f for f in all_done if not f.startswith('email_') and 'linkedin' not in f.lower()]

    print(f"[DATA] Found: {len(all_done)} tasks | {len(email_tasks)} emails | {len(linkedin_tasks)} LinkedIn posts")

    print("[DATA] Reading weekly logs...")
    logs = get_weekly_logs()

    # Generate briefing
    env = load_env()
    api_key = env.get('ANTHROPIC_API_KEY', '') or os.environ.get('ANTHROPIC_API_KEY', '')

    if api_key and api_key != "your_anthropic_api_key_here":
        print("[AI] Generating briefing with Claude API...")
        try:
            briefing_content = generate_briefing(api_key, goals, all_done, email_tasks, linkedin_tasks, logs)
            print("[OK] Briefing generated by Claude!")
            log_action("GENERATED", f"Claude API generated briefing: {briefing_filename}")
        except Exception as e:
            print(f"[WARN] Claude API failed: {e}. Using fallback.")
            briefing_content = generate_fallback_briefing(all_done, email_tasks, linkedin_tasks)
            log_action("FALLBACK", f"Used template: {e}")
    else:
        print("[WARN] ANTHROPIC_API_KEY not set. Using fallback template.")
        briefing_content = generate_fallback_briefing(all_done, email_tasks, linkedin_tasks)
        log_action("FALLBACK", "ANTHROPIC_API_KEY not configured")

    # Save briefing
    briefing_path.write_text(briefing_content, encoding='utf-8')
    print(f"\n[SAVED] {briefing_filename}")
    print(f"\n--- BRIEFING PREVIEW ---\n{briefing_content[:300]}...\n---")

    update_dashboard(briefing_path)
    log_action("SAVED", f"Briefing saved: {briefing_filename}")

    print("\n[DONE] CEO Briefing ready in vault/Briefings/")
    print("=" * 55)


if __name__ == "__main__":
    main()
